// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0JIVntd8JDIoXmVLjOzDgHZXdXD88UOE',
    appId: '1:719609494957:web:d81ba907e16f5a4ea37524',
    messagingSenderId: '719609494957',
    projectId: 'note-99a3d',
    authDomain: 'note-99a3d.firebaseapp.com',
    storageBucket: 'note-99a3d.appspot.com',
    measurementId: 'G-61SMWMHSVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0a-I_y7Qh5g82miMjWnOHm5X84XufqlY',
    appId: '1:719609494957:android:953379b45005908aa37524',
    messagingSenderId: '719609494957',
    projectId: 'note-99a3d',
    storageBucket: 'note-99a3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs1FKm9o2KFRAbtlH-olc7zeJVAVluxok',
    appId: '1:719609494957:ios:0b7e8fa426b40263a37524',
    messagingSenderId: '719609494957',
    projectId: 'note-99a3d',
    storageBucket: 'note-99a3d.appspot.com',
    iosBundleId: 'com.example.uiNotes',
  );
}
